2025-04-14 00:24:13,759 INFO    Thread-76 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002413-0gcevpwu\logs\debug.log
2025-04-14 00:24:13,759 INFO    Thread-76 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002413-0gcevpwu\logs\debug-internal.log
2025-04-14 00:24:13,759 INFO    Thread-76 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:24:13,759 INFO    Thread-76 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'GELU', 'batchNormalisation': 'no', 'dataAugmentation': 'no', 'dropout': 0.3, 'filterOrganisation': 'same', 'filters': 32}
config: {'filters': 32, 'activationFunction': 'ReLU', 'filterOrganisation': 'same', 'dataAugmentation': 'yes', 'batchNormalisation': 'yes', 'dropout': 0.2, '_wandb': {}}
2025-04-14 00:24:13,759 INFO    Thread-76 (_run_job):1788 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-04-14 00:24:14,975 INFO    Thread-76 (_run_job):1788 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment2/0gcevpwu
2025-04-14 00:24:14,990 ERROR   Thread-76 (_run_job):1788 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-04-14 00:24:14,990 INFO    Thread-76 (_run_job):1788 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-04-14 00:24:14,990 INFO    Thread-76 (_run_job):1788 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-04-14 00:24:14,991 INFO    Thread-76 (_run_job):1788 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-04-14 00:24:14,991 INFO    Thread-76 (_run_job):1788 [wandb_run.py:_restore():2322] restore
2025-04-14 00:24:14,991 INFO    Thread-76 (_run_job):1788 [wandb_run.py:_restore():2328] restore done
2025-04-14 00:24:17,111 INFO    Thread-76 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-04-14 00:24:17,111 INFO    Thread-76 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-04-14 00:24:17,111 INFO    Thread-76 (_run_job):1788 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-04-14 00:24:17,124 ERROR   MainThread:1788 [pyagent.py:_run_jobs_from_queue():234] Run 0gcevpwu errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\2340083540.py", line 36, in sweep_hyperparameters
    train_loss = train(model, train_loader, criterion, optimizer, device)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\427213304.py", line 7, in train
    outputs = model(images)
              ^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\2081958362.py", line 30, in forward
    x = self.fc(x)
        ^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x131072 and 1605632x10)

2025-04-14 00:24:21,149 INFO    MsgRouterThr:1788 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-04-14 00:24:22,130 INFO    Thread-81 (_run_job):1788 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-04-14 00:24:22,130 INFO    Thread-81 (_run_job):1788 [wandb_setup.py:_flush():67] Configure stats pid to 1788
2025-04-14 00:24:22,130 INFO    Thread-81 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from C:\Users\prajv\.config\wandb\settings
2025-04-14 00:24:22,130 INFO    Thread-81 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\settings
2025-04-14 00:24:22,130 INFO    Thread-81 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-14 00:24:22,130 INFO    Thread-81 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002422-luqzwptf\logs\debug.log
2025-04-14 00:24:22,138 INFO    Thread-81 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002422-luqzwptf\logs\debug-internal.log
2025-04-14 00:24:22,138 INFO    Thread-81 (_run_job):1788 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002CEE9D89D30>
2025-04-14 00:24:22,138 INFO    Thread-81 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:24:22,138 INFO    Thread-81 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'SiLU', 'batchNormalisation': 'yes', 'dataAugmentation': 'yes', 'dropout': 0.2, 'filterOrganisation': 'same', 'filters': 32}
config: {'_wandb': {}}
2025-04-14 00:24:22,138 INFO    Thread-81 (_run_job):1788 [wandb_init.py:init():784] starting backend
2025-04-14 00:24:22,138 INFO    Thread-81 (_run_job):1788 [wandb_init.py:init():788] sending inform_init request
2025-04-14 00:24:22,149 INFO    Thread-81 (_run_job):1788 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-04-14 00:24:22,149 INFO    Thread-81 (_run_job):1788 [wandb_init.py:init():798] backend started and connected
2025-04-14 00:24:22,153 INFO    Thread-81 (_run_job):1788 [wandb_run.py:_config_callback():1261] config_cb None None {'activationFunction': 'SiLU', 'batchNormalisation': 'yes', 'dataAugmentation': 'yes', 'dropout': 0.2, 'filterOrganisation': 'same', 'filters': 32}
2025-04-14 00:24:22,156 INFO    Thread-81 (_run_job):1788 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-04-14 00:24:22,176 INFO    Thread-81 (_run_job):1788 [wandb_init.py:init():891] updated telemetry
2025-04-14 00:24:22,239 INFO    Thread-81 (_run_job):1788 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-04-14 00:24:23,750 INFO    Thread-81 (_run_job):1788 [wandb_init.py:init():990] starting run threads in backend
2025-04-14 00:24:24,004 INFO    Thread-81 (_run_job):1788 [wandb_run.py:_console_start():2375] atexit reg
2025-04-14 00:24:24,004 INFO    Thread-81 (_run_job):1788 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-14 00:24:24,005 INFO    Thread-81 (_run_job):1788 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-14 00:24:24,005 INFO    Thread-81 (_run_job):1788 [wandb_run.py:_redirect():2315] Redirects installed.
2025-04-14 00:24:24,006 INFO    Thread-81 (_run_job):1788 [wandb_init.py:init():1032] run started, returning control to user process
2025-04-14 00:24:24,007 INFO    Thread-81 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002424-luqzwptf\logs\debug.log
2025-04-14 00:24:24,007 INFO    Thread-81 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002424-luqzwptf\logs\debug-internal.log
2025-04-14 00:24:24,007 INFO    Thread-81 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:24:24,007 INFO    Thread-81 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'SiLU', 'batchNormalisation': 'yes', 'dataAugmentation': 'yes', 'dropout': 0.2, 'filterOrganisation': 'same', 'filters': 32}
config: {'filters': 32, 'activationFunction': 'ReLU', 'filterOrganisation': 'same', 'dataAugmentation': 'yes', 'batchNormalisation': 'yes', 'dropout': 0.2, '_wandb': {}}
2025-04-14 00:24:24,007 INFO    Thread-81 (_run_job):1788 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-04-14 00:24:25,014 INFO    Thread-81 (_run_job):1788 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment2/luqzwptf
2025-04-14 00:24:25,023 ERROR   Thread-81 (_run_job):1788 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-04-14 00:24:25,023 INFO    Thread-81 (_run_job):1788 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-04-14 00:24:25,023 INFO    Thread-81 (_run_job):1788 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-04-14 00:24:25,023 INFO    Thread-81 (_run_job):1788 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-04-14 00:24:25,023 INFO    Thread-81 (_run_job):1788 [wandb_run.py:_restore():2322] restore
2025-04-14 00:24:25,023 INFO    Thread-81 (_run_job):1788 [wandb_run.py:_restore():2328] restore done
2025-04-14 00:24:26,420 INFO    Thread-81 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-04-14 00:24:26,421 INFO    Thread-81 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-04-14 00:24:26,422 INFO    Thread-81 (_run_job):1788 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-04-14 00:24:26,439 ERROR   MainThread:1788 [pyagent.py:_run_jobs_from_queue():234] Run luqzwptf errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\2340083540.py", line 36, in sweep_hyperparameters
    train_loss = train(model, train_loader, criterion, optimizer, device)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\427213304.py", line 7, in train
    outputs = model(images)
              ^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\2081958362.py", line 30, in forward
    x = self.fc(x)
        ^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x131072 and 1605632x10)

2025-04-14 00:24:26,439 ERROR   MainThread:1788 [pyagent.py:_run_jobs_from_queue():245] Detected 3 failed runs in the first 60 seconds, killing sweep.
2025-04-14 00:27:19,265 INFO    MainThread:1788 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=3
2025-04-14 00:27:20,766 INFO    MsgRouterThr:1788 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-04-14 00:27:21,744 INFO    Thread-95 (_run_job):1788 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-04-14 00:27:21,744 INFO    Thread-95 (_run_job):1788 [wandb_setup.py:_flush():67] Configure stats pid to 1788
2025-04-14 00:27:21,744 INFO    Thread-95 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from C:\Users\prajv\.config\wandb\settings
2025-04-14 00:27:21,744 INFO    Thread-95 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\settings
2025-04-14 00:27:21,744 INFO    Thread-95 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-14 00:27:21,748 INFO    Thread-95 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002721-k883j9ci\logs\debug.log
2025-04-14 00:27:21,748 INFO    Thread-95 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002721-k883j9ci\logs\debug-internal.log
2025-04-14 00:27:21,748 INFO    Thread-95 (_run_job):1788 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002CEE9A986E0>
2025-04-14 00:27:21,751 INFO    Thread-95 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:27:21,751 INFO    Thread-95 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'GELU', 'batchNormalisation': 'yes', 'dataAugmentation': 'yes', 'dropout': 0.2, 'filterOrganisation': 'same', 'filters': 64}
config: {'_wandb': {}}
2025-04-14 00:27:21,751 INFO    Thread-95 (_run_job):1788 [wandb_init.py:init():784] starting backend
2025-04-14 00:27:21,751 INFO    Thread-95 (_run_job):1788 [wandb_init.py:init():788] sending inform_init request
2025-04-14 00:27:21,751 INFO    Thread-95 (_run_job):1788 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-04-14 00:27:21,755 INFO    Thread-95 (_run_job):1788 [wandb_init.py:init():798] backend started and connected
2025-04-14 00:27:21,757 INFO    Thread-95 (_run_job):1788 [wandb_run.py:_config_callback():1261] config_cb None None {'activationFunction': 'GELU', 'batchNormalisation': 'yes', 'dataAugmentation': 'yes', 'dropout': 0.2, 'filterOrganisation': 'same', 'filters': 64}
2025-04-14 00:27:21,760 INFO    Thread-95 (_run_job):1788 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-04-14 00:27:21,778 INFO    Thread-95 (_run_job):1788 [wandb_init.py:init():891] updated telemetry
2025-04-14 00:27:21,845 INFO    Thread-95 (_run_job):1788 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-04-14 00:27:23,667 INFO    Thread-95 (_run_job):1788 [wandb_init.py:init():990] starting run threads in backend
2025-04-14 00:27:23,935 INFO    Thread-95 (_run_job):1788 [wandb_run.py:_console_start():2375] atexit reg
2025-04-14 00:27:23,937 INFO    Thread-95 (_run_job):1788 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-14 00:27:23,938 INFO    Thread-95 (_run_job):1788 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-14 00:27:23,938 INFO    Thread-95 (_run_job):1788 [wandb_run.py:_redirect():2315] Redirects installed.
2025-04-14 00:27:23,939 INFO    Thread-95 (_run_job):1788 [wandb_init.py:init():1032] run started, returning control to user process
2025-04-14 00:27:23,942 INFO    Thread-95 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002723-k883j9ci\logs\debug.log
2025-04-14 00:27:23,945 INFO    Thread-95 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002723-k883j9ci\logs\debug-internal.log
2025-04-14 00:27:23,945 INFO    Thread-95 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:27:23,945 INFO    Thread-95 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'GELU', 'batchNormalisation': 'yes', 'dataAugmentation': 'yes', 'dropout': 0.2, 'filterOrganisation': 'same', 'filters': 64}
config: {'filters': 32, 'activationFunction': 'ReLU', 'filterOrganisation': 'same', 'dataAugmentation': 'yes', 'batchNormalisation': 'yes', 'dropout': 0.2, '_wandb': {}}
2025-04-14 00:27:23,945 INFO    Thread-95 (_run_job):1788 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-04-14 00:27:24,010 INFO    Thread-95 (_run_job):1788 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment2/k883j9ci
2025-04-14 00:27:24,015 ERROR   Thread-95 (_run_job):1788 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-04-14 00:27:24,015 INFO    Thread-95 (_run_job):1788 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-04-14 00:27:24,015 INFO    Thread-95 (_run_job):1788 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-04-14 00:27:24,015 INFO    Thread-95 (_run_job):1788 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-04-14 00:27:24,015 INFO    Thread-95 (_run_job):1788 [wandb_run.py:_restore():2322] restore
2025-04-14 00:27:24,017 INFO    Thread-95 (_run_job):1788 [wandb_run.py:_restore():2328] restore done
2025-04-14 00:27:26,849 INFO    Thread-95 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-04-14 00:27:26,851 INFO    Thread-95 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-04-14 00:27:26,853 INFO    Thread-95 (_run_job):1788 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-04-14 00:27:26,867 ERROR   MainThread:1788 [pyagent.py:_run_jobs_from_queue():234] Run k883j9ci errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\2340083540.py", line 30, in sweep_hyperparameters
    model = ConfigurableCNN(config).to(device)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\4267389434.py", line 7, in __init__
    for out_channels in [config.filters] * layers:
                        ~~~~~~~~~~~~~~~~~^~~~~~~~
TypeError: can't multiply sequence by non-int of type 'list'

2025-04-14 00:27:31,892 INFO    MsgRouterThr:1788 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-04-14 00:27:32,887 INFO    Thread-100 (_run_job):1788 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-04-14 00:27:32,887 INFO    Thread-100 (_run_job):1788 [wandb_setup.py:_flush():67] Configure stats pid to 1788
2025-04-14 00:27:32,887 INFO    Thread-100 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from C:\Users\prajv\.config\wandb\settings
2025-04-14 00:27:32,903 INFO    Thread-100 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\settings
2025-04-14 00:27:32,903 INFO    Thread-100 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-14 00:27:32,903 INFO    Thread-100 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002732-4p8nneic\logs\debug.log
2025-04-14 00:27:32,906 INFO    Thread-100 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002732-4p8nneic\logs\debug-internal.log
2025-04-14 00:27:32,909 INFO    Thread-100 (_run_job):1788 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002CEEA1EEC60>
2025-04-14 00:27:32,909 INFO    Thread-100 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:27:32,911 INFO    Thread-100 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'SiLU', 'batchNormalisation': 'no', 'dataAugmentation': 'no', 'dropout': 0.2, 'filterOrganisation': 'double', 'filters': 64}
config: {'_wandb': {}}
2025-04-14 00:27:32,911 INFO    Thread-100 (_run_job):1788 [wandb_init.py:init():784] starting backend
2025-04-14 00:27:32,911 INFO    Thread-100 (_run_job):1788 [wandb_init.py:init():788] sending inform_init request
2025-04-14 00:27:32,919 INFO    Thread-100 (_run_job):1788 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-04-14 00:27:32,919 INFO    Thread-100 (_run_job):1788 [wandb_init.py:init():798] backend started and connected
2025-04-14 00:27:32,922 INFO    Thread-100 (_run_job):1788 [wandb_run.py:_config_callback():1261] config_cb None None {'activationFunction': 'SiLU', 'batchNormalisation': 'no', 'dataAugmentation': 'no', 'dropout': 0.2, 'filterOrganisation': 'double', 'filters': 64}
2025-04-14 00:27:32,924 INFO    Thread-100 (_run_job):1788 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-04-14 00:27:32,948 INFO    Thread-100 (_run_job):1788 [wandb_init.py:init():891] updated telemetry
2025-04-14 00:27:33,011 INFO    Thread-100 (_run_job):1788 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-04-14 00:27:34,518 INFO    Thread-100 (_run_job):1788 [wandb_init.py:init():990] starting run threads in backend
2025-04-14 00:27:34,763 INFO    Thread-100 (_run_job):1788 [wandb_run.py:_console_start():2375] atexit reg
2025-04-14 00:27:34,765 INFO    Thread-100 (_run_job):1788 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-14 00:27:34,765 INFO    Thread-100 (_run_job):1788 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-14 00:27:34,765 INFO    Thread-100 (_run_job):1788 [wandb_run.py:_redirect():2315] Redirects installed.
2025-04-14 00:27:34,766 INFO    Thread-100 (_run_job):1788 [wandb_init.py:init():1032] run started, returning control to user process
2025-04-14 00:27:34,767 INFO    Thread-100 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002734-4p8nneic\logs\debug.log
2025-04-14 00:27:34,767 INFO    Thread-100 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002734-4p8nneic\logs\debug-internal.log
2025-04-14 00:27:34,767 INFO    Thread-100 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:27:34,767 INFO    Thread-100 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'SiLU', 'batchNormalisation': 'no', 'dataAugmentation': 'no', 'dropout': 0.2, 'filterOrganisation': 'double', 'filters': 64}
config: {'filters': 32, 'activationFunction': 'ReLU', 'filterOrganisation': 'same', 'dataAugmentation': 'yes', 'batchNormalisation': 'yes', 'dropout': 0.2, '_wandb': {}}
2025-04-14 00:27:34,767 INFO    Thread-100 (_run_job):1788 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-04-14 00:27:34,827 INFO    Thread-100 (_run_job):1788 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment2/4p8nneic
2025-04-14 00:27:34,831 ERROR   Thread-100 (_run_job):1788 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-04-14 00:27:34,831 INFO    Thread-100 (_run_job):1788 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-04-14 00:27:34,831 INFO    Thread-100 (_run_job):1788 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-04-14 00:27:34,831 INFO    Thread-100 (_run_job):1788 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-04-14 00:27:34,831 INFO    Thread-100 (_run_job):1788 [wandb_run.py:_restore():2322] restore
2025-04-14 00:27:34,831 INFO    Thread-100 (_run_job):1788 [wandb_run.py:_restore():2328] restore done
2025-04-14 00:27:37,702 INFO    Thread-100 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-04-14 00:27:37,702 INFO    Thread-100 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-04-14 00:27:37,702 INFO    Thread-100 (_run_job):1788 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-04-14 00:27:37,717 ERROR   MainThread:1788 [pyagent.py:_run_jobs_from_queue():234] Run 4p8nneic errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\2340083540.py", line 30, in sweep_hyperparameters
    model = ConfigurableCNN(config).to(device)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\4267389434.py", line 7, in __init__
    for out_channels in [config.filters] * layers:
                        ~~~~~~~~~~~~~~~~~^~~~~~~~
TypeError: can't multiply sequence by non-int of type 'list'

2025-04-14 00:27:41,723 INFO    MsgRouterThr:1788 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-04-14 00:27:42,714 INFO    Thread-105 (_run_job):1788 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-04-14 00:27:42,721 INFO    Thread-105 (_run_job):1788 [wandb_setup.py:_flush():67] Configure stats pid to 1788
2025-04-14 00:27:42,721 INFO    Thread-105 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from C:\Users\prajv\.config\wandb\settings
2025-04-14 00:27:42,722 INFO    Thread-105 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\settings
2025-04-14 00:27:42,722 INFO    Thread-105 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-14 00:27:42,722 INFO    Thread-105 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002742-dkhlbx0h\logs\debug.log
2025-04-14 00:27:42,722 INFO    Thread-105 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002742-dkhlbx0h\logs\debug-internal.log
2025-04-14 00:27:42,722 INFO    Thread-105 (_run_job):1788 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002CEEA1FBB30>
2025-04-14 00:27:42,722 INFO    Thread-105 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:27:42,722 INFO    Thread-105 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'SiLU', 'batchNormalisation': 'no', 'dataAugmentation': 'no', 'dropout': 0.3, 'filterOrganisation': 'half', 'filters': 64}
config: {'_wandb': {}}
2025-04-14 00:27:42,722 INFO    Thread-105 (_run_job):1788 [wandb_init.py:init():784] starting backend
2025-04-14 00:27:42,722 INFO    Thread-105 (_run_job):1788 [wandb_init.py:init():788] sending inform_init request
2025-04-14 00:27:42,722 INFO    Thread-105 (_run_job):1788 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-04-14 00:27:42,729 INFO    Thread-105 (_run_job):1788 [wandb_init.py:init():798] backend started and connected
2025-04-14 00:27:42,730 INFO    Thread-105 (_run_job):1788 [wandb_run.py:_config_callback():1261] config_cb None None {'activationFunction': 'SiLU', 'batchNormalisation': 'no', 'dataAugmentation': 'no', 'dropout': 0.3, 'filterOrganisation': 'half', 'filters': 64}
2025-04-14 00:27:42,731 INFO    Thread-105 (_run_job):1788 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-04-14 00:27:42,757 INFO    Thread-105 (_run_job):1788 [wandb_init.py:init():891] updated telemetry
2025-04-14 00:27:42,841 INFO    Thread-105 (_run_job):1788 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-04-14 00:27:44,348 INFO    Thread-105 (_run_job):1788 [wandb_init.py:init():990] starting run threads in backend
2025-04-14 00:27:44,575 INFO    Thread-105 (_run_job):1788 [wandb_run.py:_console_start():2375] atexit reg
2025-04-14 00:27:44,577 INFO    Thread-105 (_run_job):1788 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-14 00:27:44,577 INFO    Thread-105 (_run_job):1788 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-14 00:27:44,577 INFO    Thread-105 (_run_job):1788 [wandb_run.py:_redirect():2315] Redirects installed.
2025-04-14 00:27:44,578 INFO    Thread-105 (_run_job):1788 [wandb_init.py:init():1032] run started, returning control to user process
2025-04-14 00:27:44,581 INFO    Thread-105 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002744-dkhlbx0h\logs\debug.log
2025-04-14 00:27:44,581 INFO    Thread-105 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002744-dkhlbx0h\logs\debug-internal.log
2025-04-14 00:27:44,581 INFO    Thread-105 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:27:44,581 INFO    Thread-105 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'SiLU', 'batchNormalisation': 'no', 'dataAugmentation': 'no', 'dropout': 0.3, 'filterOrganisation': 'half', 'filters': 64}
config: {'filters': 32, 'activationFunction': 'ReLU', 'filterOrganisation': 'same', 'dataAugmentation': 'yes', 'batchNormalisation': 'yes', 'dropout': 0.2, '_wandb': {}}
2025-04-14 00:27:44,581 INFO    Thread-105 (_run_job):1788 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-04-14 00:27:44,641 INFO    Thread-105 (_run_job):1788 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment2/dkhlbx0h
2025-04-14 00:27:44,643 ERROR   Thread-105 (_run_job):1788 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-04-14 00:27:44,643 INFO    Thread-105 (_run_job):1788 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-04-14 00:27:44,643 INFO    Thread-105 (_run_job):1788 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-04-14 00:27:44,643 INFO    Thread-105 (_run_job):1788 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-04-14 00:27:44,643 INFO    Thread-105 (_run_job):1788 [wandb_run.py:_restore():2322] restore
2025-04-14 00:27:44,643 INFO    Thread-105 (_run_job):1788 [wandb_run.py:_restore():2328] restore done
2025-04-14 00:27:47,400 INFO    Thread-105 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-04-14 00:27:47,402 INFO    Thread-105 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-04-14 00:27:47,402 INFO    Thread-105 (_run_job):1788 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-04-14 00:27:47,418 ERROR   MainThread:1788 [pyagent.py:_run_jobs_from_queue():234] Run dkhlbx0h errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\2340083540.py", line 30, in sweep_hyperparameters
    model = ConfigurableCNN(config).to(device)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\4267389434.py", line 7, in __init__
    for out_channels in [config.filters] * layers:
                        ~~~~~~~~~~~~~~~~~^~~~~~~~
TypeError: can't multiply sequence by non-int of type 'list'

2025-04-14 00:27:47,425 ERROR   MainThread:1788 [pyagent.py:_run_jobs_from_queue():245] Detected 3 failed runs in the first 60 seconds, killing sweep.
2025-04-14 00:28:29,604 INFO    MainThread:1788 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=3
2025-04-14 00:28:30,706 INFO    MsgRouterThr:1788 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-04-14 00:28:31,677 INFO    Thread-131 (_run_job):1788 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-04-14 00:28:31,677 INFO    Thread-131 (_run_job):1788 [wandb_setup.py:_flush():67] Configure stats pid to 1788
2025-04-14 00:28:31,677 INFO    Thread-131 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from C:\Users\prajv\.config\wandb\settings
2025-04-14 00:28:31,677 INFO    Thread-131 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\settings
2025-04-14 00:28:31,677 INFO    Thread-131 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-14 00:28:31,677 INFO    Thread-131 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002831-80a9qc9k\logs\debug.log
2025-04-14 00:28:31,685 INFO    Thread-131 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002831-80a9qc9k\logs\debug-internal.log
2025-04-14 00:28:31,685 INFO    Thread-131 (_run_job):1788 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002CEEA873710>
2025-04-14 00:28:31,685 INFO    Thread-131 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:28:31,690 INFO    Thread-131 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'SiLU', 'batchNormalisation': 'no', 'dataAugmentation': 'yes', 'dropout': 0.3, 'filterOrganisation': 'double', 'filters': 64}
config: {'_wandb': {}}
2025-04-14 00:28:31,690 INFO    Thread-131 (_run_job):1788 [wandb_init.py:init():784] starting backend
2025-04-14 00:28:31,690 INFO    Thread-131 (_run_job):1788 [wandb_init.py:init():788] sending inform_init request
2025-04-14 00:28:31,693 INFO    Thread-131 (_run_job):1788 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-04-14 00:28:31,698 INFO    Thread-131 (_run_job):1788 [wandb_init.py:init():798] backend started and connected
2025-04-14 00:28:31,701 INFO    Thread-131 (_run_job):1788 [wandb_run.py:_config_callback():1261] config_cb None None {'activationFunction': 'SiLU', 'batchNormalisation': 'no', 'dataAugmentation': 'yes', 'dropout': 0.3, 'filterOrganisation': 'double', 'filters': 64}
2025-04-14 00:28:31,703 INFO    Thread-131 (_run_job):1788 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-04-14 00:28:31,728 INFO    Thread-131 (_run_job):1788 [wandb_init.py:init():891] updated telemetry
2025-04-14 00:28:31,787 INFO    Thread-131 (_run_job):1788 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-04-14 00:28:33,397 INFO    Thread-131 (_run_job):1788 [wandb_init.py:init():990] starting run threads in backend
2025-04-14 00:28:33,618 INFO    Thread-131 (_run_job):1788 [wandb_run.py:_console_start():2375] atexit reg
2025-04-14 00:28:33,619 INFO    Thread-131 (_run_job):1788 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-14 00:28:33,619 INFO    Thread-131 (_run_job):1788 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-14 00:28:33,620 INFO    Thread-131 (_run_job):1788 [wandb_run.py:_redirect():2315] Redirects installed.
2025-04-14 00:28:33,621 INFO    Thread-131 (_run_job):1788 [wandb_init.py:init():1032] run started, returning control to user process
2025-04-14 00:28:33,626 INFO    Thread-131 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002833-80a9qc9k\logs\debug.log
2025-04-14 00:28:33,626 INFO    Thread-131 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002833-80a9qc9k\logs\debug-internal.log
2025-04-14 00:28:33,626 INFO    Thread-131 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:28:33,626 INFO    Thread-131 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'SiLU', 'batchNormalisation': 'no', 'dataAugmentation': 'yes', 'dropout': 0.3, 'filterOrganisation': 'double', 'filters': 64}
config: {'filters': 32, 'activationFunction': 'ReLU', 'filterOrganisation': 'same', 'dataAugmentation': 'yes', 'batchNormalisation': 'yes', 'dropout': 0.2, '_wandb': {}}
2025-04-14 00:28:33,626 INFO    Thread-131 (_run_job):1788 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-04-14 00:28:33,679 INFO    Thread-131 (_run_job):1788 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment2/80a9qc9k
2025-04-14 00:28:33,686 ERROR   Thread-131 (_run_job):1788 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-04-14 00:28:33,686 INFO    Thread-131 (_run_job):1788 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-04-14 00:28:33,686 INFO    Thread-131 (_run_job):1788 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-04-14 00:28:33,686 INFO    Thread-131 (_run_job):1788 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-04-14 00:28:33,686 INFO    Thread-131 (_run_job):1788 [wandb_run.py:_restore():2322] restore
2025-04-14 00:28:33,686 INFO    Thread-131 (_run_job):1788 [wandb_run.py:_restore():2328] restore done
2025-04-14 00:28:36,045 INFO    Thread-131 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-04-14 00:28:36,045 INFO    Thread-131 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-04-14 00:28:36,045 INFO    Thread-131 (_run_job):1788 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-04-14 00:28:36,053 ERROR   MainThread:1788 [pyagent.py:_run_jobs_from_queue():234] Run 80a9qc9k errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\2340083540.py", line 30, in sweep_hyperparameters
    model = ConfigurableCNN(config).to(device)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\1040758951.py", line 11, in __init__
    layers.append(afMap[config.activationFunction()])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object is not callable

2025-04-14 00:28:46,130 INFO    MsgRouterThr:1788 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-04-14 00:28:47,139 INFO    Thread-136 (_run_job):1788 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-04-14 00:28:47,139 INFO    Thread-136 (_run_job):1788 [wandb_setup.py:_flush():67] Configure stats pid to 1788
2025-04-14 00:28:47,145 INFO    Thread-136 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from C:\Users\prajv\.config\wandb\settings
2025-04-14 00:28:47,147 INFO    Thread-136 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\settings
2025-04-14 00:28:47,147 INFO    Thread-136 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-14 00:28:47,147 INFO    Thread-136 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002847-yd4p9mkf\logs\debug.log
2025-04-14 00:28:47,147 INFO    Thread-136 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002847-yd4p9mkf\logs\debug-internal.log
2025-04-14 00:28:47,147 INFO    Thread-136 (_run_job):1788 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002CEE9CBE150>
2025-04-14 00:28:47,154 INFO    Thread-136 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:28:47,155 INFO    Thread-136 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'Mish', 'batchNormalisation': 'yes', 'dataAugmentation': 'yes', 'dropout': 0.3, 'filterOrganisation': 'double', 'filters': 64}
config: {'_wandb': {}}
2025-04-14 00:28:47,155 INFO    Thread-136 (_run_job):1788 [wandb_init.py:init():784] starting backend
2025-04-14 00:28:47,155 INFO    Thread-136 (_run_job):1788 [wandb_init.py:init():788] sending inform_init request
2025-04-14 00:28:47,162 INFO    Thread-136 (_run_job):1788 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-04-14 00:28:47,163 INFO    Thread-136 (_run_job):1788 [wandb_init.py:init():798] backend started and connected
2025-04-14 00:28:47,166 INFO    Thread-136 (_run_job):1788 [wandb_run.py:_config_callback():1261] config_cb None None {'activationFunction': 'Mish', 'batchNormalisation': 'yes', 'dataAugmentation': 'yes', 'dropout': 0.3, 'filterOrganisation': 'double', 'filters': 64}
2025-04-14 00:28:47,168 INFO    Thread-136 (_run_job):1788 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-04-14 00:28:47,188 INFO    Thread-136 (_run_job):1788 [wandb_init.py:init():891] updated telemetry
2025-04-14 00:28:47,251 INFO    Thread-136 (_run_job):1788 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-04-14 00:28:48,858 INFO    Thread-136 (_run_job):1788 [wandb_init.py:init():990] starting run threads in backend
2025-04-14 00:28:49,102 INFO    Thread-136 (_run_job):1788 [wandb_run.py:_console_start():2375] atexit reg
2025-04-14 00:28:49,103 INFO    Thread-136 (_run_job):1788 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-14 00:28:49,104 INFO    Thread-136 (_run_job):1788 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-14 00:28:49,105 INFO    Thread-136 (_run_job):1788 [wandb_run.py:_redirect():2315] Redirects installed.
2025-04-14 00:28:49,106 INFO    Thread-136 (_run_job):1788 [wandb_init.py:init():1032] run started, returning control to user process
2025-04-14 00:28:49,108 INFO    Thread-136 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002849-yd4p9mkf\logs\debug.log
2025-04-14 00:28:49,108 INFO    Thread-136 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002849-yd4p9mkf\logs\debug-internal.log
2025-04-14 00:28:49,108 INFO    Thread-136 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:28:49,108 INFO    Thread-136 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'Mish', 'batchNormalisation': 'yes', 'dataAugmentation': 'yes', 'dropout': 0.3, 'filterOrganisation': 'double', 'filters': 64}
config: {'filters': 32, 'activationFunction': 'ReLU', 'filterOrganisation': 'same', 'dataAugmentation': 'yes', 'batchNormalisation': 'yes', 'dropout': 0.2, '_wandb': {}}
2025-04-14 00:28:49,108 INFO    Thread-136 (_run_job):1788 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-04-14 00:28:49,167 INFO    Thread-136 (_run_job):1788 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment2/yd4p9mkf
2025-04-14 00:28:49,170 ERROR   Thread-136 (_run_job):1788 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-04-14 00:28:49,170 INFO    Thread-136 (_run_job):1788 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-04-14 00:28:49,170 INFO    Thread-136 (_run_job):1788 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-04-14 00:28:49,171 INFO    Thread-136 (_run_job):1788 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-04-14 00:28:49,171 INFO    Thread-136 (_run_job):1788 [wandb_run.py:_restore():2322] restore
2025-04-14 00:28:49,172 INFO    Thread-136 (_run_job):1788 [wandb_run.py:_restore():2328] restore done
2025-04-14 00:28:52,343 INFO    Thread-136 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-04-14 00:28:52,343 INFO    Thread-136 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-04-14 00:28:52,343 INFO    Thread-136 (_run_job):1788 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-04-14 00:28:52,350 ERROR   MainThread:1788 [pyagent.py:_run_jobs_from_queue():234] Run yd4p9mkf errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\2340083540.py", line 30, in sweep_hyperparameters
    model = ConfigurableCNN(config).to(device)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\1040758951.py", line 11, in __init__
    layers.append(afMap[config.activationFunction()])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object is not callable

2025-04-14 00:29:02,387 INFO    MsgRouterThr:1788 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-04-14 00:29:03,500 INFO    Thread-141 (_run_job):1788 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-04-14 00:29:03,500 INFO    Thread-141 (_run_job):1788 [wandb_setup.py:_flush():67] Configure stats pid to 1788
2025-04-14 00:29:03,500 INFO    Thread-141 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from C:\Users\prajv\.config\wandb\settings
2025-04-14 00:29:03,500 INFO    Thread-141 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\settings
2025-04-14 00:29:03,516 INFO    Thread-141 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-14 00:29:03,516 INFO    Thread-141 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002903-tidhm9fg\logs\debug.log
2025-04-14 00:29:03,516 INFO    Thread-141 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002903-tidhm9fg\logs\debug-internal.log
2025-04-14 00:29:03,516 INFO    Thread-141 (_run_job):1788 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002CEEA63F860>
2025-04-14 00:29:03,516 INFO    Thread-141 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:29:03,516 INFO    Thread-141 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'GELU', 'batchNormalisation': 'no', 'dataAugmentation': 'no', 'dropout': 0.3, 'filterOrganisation': 'half', 'filters': 32}
config: {'_wandb': {}}
2025-04-14 00:29:03,519 INFO    Thread-141 (_run_job):1788 [wandb_init.py:init():784] starting backend
2025-04-14 00:29:03,519 INFO    Thread-141 (_run_job):1788 [wandb_init.py:init():788] sending inform_init request
2025-04-14 00:29:03,520 INFO    Thread-141 (_run_job):1788 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-04-14 00:29:03,523 INFO    Thread-141 (_run_job):1788 [wandb_init.py:init():798] backend started and connected
2025-04-14 00:29:03,524 INFO    Thread-141 (_run_job):1788 [wandb_run.py:_config_callback():1261] config_cb None None {'activationFunction': 'GELU', 'batchNormalisation': 'no', 'dataAugmentation': 'no', 'dropout': 0.3, 'filterOrganisation': 'half', 'filters': 32}
2025-04-14 00:29:03,525 INFO    Thread-141 (_run_job):1788 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-04-14 00:29:03,541 INFO    Thread-141 (_run_job):1788 [wandb_init.py:init():891] updated telemetry
2025-04-14 00:29:03,610 INFO    Thread-141 (_run_job):1788 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-04-14 00:29:05,139 INFO    Thread-141 (_run_job):1788 [wandb_init.py:init():990] starting run threads in backend
2025-04-14 00:29:05,451 INFO    Thread-141 (_run_job):1788 [wandb_run.py:_console_start():2375] atexit reg
2025-04-14 00:29:05,452 INFO    Thread-141 (_run_job):1788 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-14 00:29:05,453 INFO    Thread-141 (_run_job):1788 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-14 00:29:05,453 INFO    Thread-141 (_run_job):1788 [wandb_run.py:_redirect():2315] Redirects installed.
2025-04-14 00:29:05,456 INFO    Thread-141 (_run_job):1788 [wandb_init.py:init():1032] run started, returning control to user process
2025-04-14 00:29:05,461 INFO    Thread-141 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002905-tidhm9fg\logs\debug.log
2025-04-14 00:29:05,462 INFO    Thread-141 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002905-tidhm9fg\logs\debug-internal.log
2025-04-14 00:29:05,463 INFO    Thread-141 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:29:05,464 INFO    Thread-141 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'GELU', 'batchNormalisation': 'no', 'dataAugmentation': 'no', 'dropout': 0.3, 'filterOrganisation': 'half', 'filters': 32}
config: {'filters': 32, 'activationFunction': 'ReLU', 'filterOrganisation': 'same', 'dataAugmentation': 'yes', 'batchNormalisation': 'yes', 'dropout': 0.2, '_wandb': {}}
2025-04-14 00:29:05,464 INFO    Thread-141 (_run_job):1788 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-04-14 00:29:05,530 INFO    Thread-141 (_run_job):1788 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment2/tidhm9fg
2025-04-14 00:29:05,534 ERROR   Thread-141 (_run_job):1788 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-04-14 00:29:05,534 INFO    Thread-141 (_run_job):1788 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-04-14 00:29:05,534 INFO    Thread-141 (_run_job):1788 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-04-14 00:29:05,535 INFO    Thread-141 (_run_job):1788 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-04-14 00:29:05,535 INFO    Thread-141 (_run_job):1788 [wandb_run.py:_restore():2322] restore
2025-04-14 00:29:05,536 INFO    Thread-141 (_run_job):1788 [wandb_run.py:_restore():2328] restore done
2025-04-14 00:29:08,425 INFO    Thread-141 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-04-14 00:29:08,425 INFO    Thread-141 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-04-14 00:29:08,425 INFO    Thread-141 (_run_job):1788 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-04-14 00:29:08,431 ERROR   MainThread:1788 [pyagent.py:_run_jobs_from_queue():234] Run tidhm9fg errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\2340083540.py", line 30, in sweep_hyperparameters
    model = ConfigurableCNN(config).to(device)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\1040758951.py", line 11, in __init__
    layers.append(afMap[config.activationFunction()])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object is not callable

2025-04-14 00:29:08,432 ERROR   MainThread:1788 [pyagent.py:_run_jobs_from_queue():245] Detected 3 failed runs in the first 60 seconds, killing sweep.
2025-04-14 00:29:19,365 INFO    MainThread:1788 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=3
2025-04-14 00:29:20,501 INFO    MsgRouterThr:1788 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-04-14 00:29:21,448 INFO    Thread-147 (_run_job):1788 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-04-14 00:29:21,448 INFO    Thread-147 (_run_job):1788 [wandb_setup.py:_flush():67] Configure stats pid to 1788
2025-04-14 00:29:21,448 INFO    Thread-147 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from C:\Users\prajv\.config\wandb\settings
2025-04-14 00:29:21,448 INFO    Thread-147 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\settings
2025-04-14 00:29:21,448 INFO    Thread-147 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-14 00:29:21,448 INFO    Thread-147 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002921-b4u6zp73\logs\debug.log
2025-04-14 00:29:21,456 INFO    Thread-147 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002921-b4u6zp73\logs\debug-internal.log
2025-04-14 00:29:21,457 INFO    Thread-147 (_run_job):1788 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002CEEACE3C80>
2025-04-14 00:29:21,458 INFO    Thread-147 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:29:21,459 INFO    Thread-147 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'SiLU', 'batchNormalisation': 'yes', 'dataAugmentation': 'no', 'dropout': 0.2, 'filterOrganisation': 'half', 'filters': 32}
config: {'_wandb': {}}
2025-04-14 00:29:21,459 INFO    Thread-147 (_run_job):1788 [wandb_init.py:init():784] starting backend
2025-04-14 00:29:21,459 INFO    Thread-147 (_run_job):1788 [wandb_init.py:init():788] sending inform_init request
2025-04-14 00:29:21,463 INFO    Thread-147 (_run_job):1788 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-04-14 00:29:21,464 INFO    Thread-147 (_run_job):1788 [wandb_init.py:init():798] backend started and connected
2025-04-14 00:29:21,466 INFO    Thread-147 (_run_job):1788 [wandb_run.py:_config_callback():1261] config_cb None None {'activationFunction': 'SiLU', 'batchNormalisation': 'yes', 'dataAugmentation': 'no', 'dropout': 0.2, 'filterOrganisation': 'half', 'filters': 32}
2025-04-14 00:29:21,468 INFO    Thread-147 (_run_job):1788 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-04-14 00:29:21,485 INFO    Thread-147 (_run_job):1788 [wandb_init.py:init():891] updated telemetry
2025-04-14 00:29:21,547 INFO    Thread-147 (_run_job):1788 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-04-14 00:29:23,061 INFO    Thread-147 (_run_job):1788 [wandb_init.py:init():990] starting run threads in backend
2025-04-14 00:29:23,312 INFO    Thread-147 (_run_job):1788 [wandb_run.py:_console_start():2375] atexit reg
2025-04-14 00:29:23,312 INFO    Thread-147 (_run_job):1788 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-14 00:29:23,312 INFO    Thread-147 (_run_job):1788 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-14 00:29:23,313 INFO    Thread-147 (_run_job):1788 [wandb_run.py:_redirect():2315] Redirects installed.
2025-04-14 00:29:23,314 INFO    Thread-147 (_run_job):1788 [wandb_init.py:init():1032] run started, returning control to user process
2025-04-14 00:29:23,315 INFO    Thread-147 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002923-b4u6zp73\logs\debug.log
2025-04-14 00:29:23,315 INFO    Thread-147 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002923-b4u6zp73\logs\debug-internal.log
2025-04-14 00:29:23,315 INFO    Thread-147 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:29:23,315 INFO    Thread-147 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'SiLU', 'batchNormalisation': 'yes', 'dataAugmentation': 'no', 'dropout': 0.2, 'filterOrganisation': 'half', 'filters': 32}
config: {'filters': 32, 'activationFunction': 'ReLU', 'filterOrganisation': 'same', 'dataAugmentation': 'yes', 'batchNormalisation': 'yes', 'dropout': 0.2, '_wandb': {}}
2025-04-14 00:29:23,315 INFO    Thread-147 (_run_job):1788 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-04-14 00:29:24,427 INFO    Thread-147 (_run_job):1788 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment2/b4u6zp73
2025-04-14 00:29:24,432 ERROR   Thread-147 (_run_job):1788 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-04-14 00:29:24,432 INFO    Thread-147 (_run_job):1788 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-04-14 00:29:24,432 INFO    Thread-147 (_run_job):1788 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-04-14 00:29:24,432 INFO    Thread-147 (_run_job):1788 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-04-14 00:29:24,432 INFO    Thread-147 (_run_job):1788 [wandb_run.py:_restore():2322] restore
2025-04-14 00:29:24,432 INFO    Thread-147 (_run_job):1788 [wandb_run.py:_restore():2328] restore done
2025-04-14 00:29:26,552 INFO    Thread-147 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-04-14 00:29:26,554 INFO    Thread-147 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-04-14 00:29:26,556 INFO    Thread-147 (_run_job):1788 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-04-14 00:29:26,576 ERROR   MainThread:1788 [pyagent.py:_run_jobs_from_queue():234] Run b4u6zp73 errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\2340083540.py", line 36, in sweep_hyperparameters
    train_loss = train(model, train_loader, criterion, optimizer, device)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\427213304.py", line 7, in train
    outputs = model(images)
              ^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\2929947945.py", line 36, in forward
    x = self.fc(x)
        ^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\container.py", line 250, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x131072 and 1605632x10)

2025-04-14 00:29:31,581 INFO    MsgRouterThr:1788 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-04-14 00:29:32,602 INFO    Thread-152 (_run_job):1788 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-04-14 00:29:32,602 INFO    Thread-152 (_run_job):1788 [wandb_setup.py:_flush():67] Configure stats pid to 1788
2025-04-14 00:29:32,607 INFO    Thread-152 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from C:\Users\prajv\.config\wandb\settings
2025-04-14 00:29:32,609 INFO    Thread-152 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\settings
2025-04-14 00:29:32,609 INFO    Thread-152 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-14 00:29:32,609 INFO    Thread-152 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002932-mwceu5cv\logs\debug.log
2025-04-14 00:29:32,609 INFO    Thread-152 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002932-mwceu5cv\logs\debug-internal.log
2025-04-14 00:29:32,614 INFO    Thread-152 (_run_job):1788 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002CEEAAC0A70>
2025-04-14 00:29:32,615 INFO    Thread-152 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:29:32,615 INFO    Thread-152 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'ReLU', 'batchNormalisation': 'yes', 'dataAugmentation': 'no', 'dropout': 0.3, 'filterOrganisation': 'same', 'filters': 32}
config: {'_wandb': {}}
2025-04-14 00:29:32,615 INFO    Thread-152 (_run_job):1788 [wandb_init.py:init():784] starting backend
2025-04-14 00:29:32,615 INFO    Thread-152 (_run_job):1788 [wandb_init.py:init():788] sending inform_init request
2025-04-14 00:29:32,615 INFO    Thread-152 (_run_job):1788 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-04-14 00:29:32,623 INFO    Thread-152 (_run_job):1788 [wandb_init.py:init():798] backend started and connected
2025-04-14 00:29:32,625 INFO    Thread-152 (_run_job):1788 [wandb_run.py:_config_callback():1261] config_cb None None {'activationFunction': 'ReLU', 'batchNormalisation': 'yes', 'dataAugmentation': 'no', 'dropout': 0.3, 'filterOrganisation': 'same', 'filters': 32}
2025-04-14 00:29:32,627 INFO    Thread-152 (_run_job):1788 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-04-14 00:29:32,647 INFO    Thread-152 (_run_job):1788 [wandb_init.py:init():891] updated telemetry
2025-04-14 00:29:32,707 INFO    Thread-152 (_run_job):1788 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-04-14 00:29:34,122 INFO    Thread-152 (_run_job):1788 [wandb_init.py:init():990] starting run threads in backend
2025-04-14 00:29:34,358 INFO    Thread-152 (_run_job):1788 [wandb_run.py:_console_start():2375] atexit reg
2025-04-14 00:29:34,359 INFO    Thread-152 (_run_job):1788 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-14 00:29:34,360 INFO    Thread-152 (_run_job):1788 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-14 00:29:34,360 INFO    Thread-152 (_run_job):1788 [wandb_run.py:_redirect():2315] Redirects installed.
2025-04-14 00:29:34,361 INFO    Thread-152 (_run_job):1788 [wandb_init.py:init():1032] run started, returning control to user process
2025-04-14 00:29:34,366 INFO    Thread-152 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002934-mwceu5cv\logs\debug.log
2025-04-14 00:29:34,366 INFO    Thread-152 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002934-mwceu5cv\logs\debug-internal.log
2025-04-14 00:29:34,368 INFO    Thread-152 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:29:34,368 INFO    Thread-152 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'ReLU', 'batchNormalisation': 'yes', 'dataAugmentation': 'no', 'dropout': 0.3, 'filterOrganisation': 'same', 'filters': 32}
config: {'filters': 32, 'activationFunction': 'ReLU', 'filterOrganisation': 'same', 'dataAugmentation': 'yes', 'batchNormalisation': 'yes', 'dropout': 0.2, '_wandb': {}}
2025-04-14 00:29:34,369 INFO    Thread-152 (_run_job):1788 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-04-14 00:29:35,490 INFO    Thread-152 (_run_job):1788 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment2/mwceu5cv
2025-04-14 00:29:35,500 ERROR   Thread-152 (_run_job):1788 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-04-14 00:29:35,500 INFO    Thread-152 (_run_job):1788 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-04-14 00:29:35,500 INFO    Thread-152 (_run_job):1788 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-04-14 00:29:35,500 INFO    Thread-152 (_run_job):1788 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-04-14 00:29:35,500 INFO    Thread-152 (_run_job):1788 [wandb_run.py:_restore():2322] restore
2025-04-14 00:29:35,500 INFO    Thread-152 (_run_job):1788 [wandb_run.py:_restore():2328] restore done
2025-04-14 00:29:37,509 INFO    Thread-152 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-04-14 00:29:37,509 INFO    Thread-152 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-04-14 00:29:37,509 INFO    Thread-152 (_run_job):1788 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-04-14 00:29:37,524 ERROR   MainThread:1788 [pyagent.py:_run_jobs_from_queue():234] Run mwceu5cv errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\2340083540.py", line 36, in sweep_hyperparameters
    train_loss = train(model, train_loader, criterion, optimizer, device)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\427213304.py", line 7, in train
    outputs = model(images)
              ^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\2929947945.py", line 36, in forward
    x = self.fc(x)
        ^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\container.py", line 250, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x131072 and 1605632x10)

2025-04-14 00:29:42,550 INFO    MsgRouterThr:1788 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-04-14 00:29:43,549 INFO    Thread-157 (_run_job):1788 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-04-14 00:29:43,549 INFO    Thread-157 (_run_job):1788 [wandb_setup.py:_flush():67] Configure stats pid to 1788
2025-04-14 00:29:43,549 INFO    Thread-157 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from C:\Users\prajv\.config\wandb\settings
2025-04-14 00:29:43,549 INFO    Thread-157 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\settings
2025-04-14 00:29:43,549 INFO    Thread-157 (_run_job):1788 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-14 00:29:43,549 INFO    Thread-157 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002943-cziyfmuk\logs\debug.log
2025-04-14 00:29:43,549 INFO    Thread-157 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002943-cziyfmuk\logs\debug-internal.log
2025-04-14 00:29:43,555 INFO    Thread-157 (_run_job):1788 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002CEEACE2F00>
2025-04-14 00:29:43,555 INFO    Thread-157 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:29:43,557 INFO    Thread-157 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'GELU', 'batchNormalisation': 'no', 'dataAugmentation': 'no', 'dropout': 0.3, 'filterOrganisation': 'same', 'filters': 64}
config: {'_wandb': {}}
2025-04-14 00:29:43,557 INFO    Thread-157 (_run_job):1788 [wandb_init.py:init():784] starting backend
2025-04-14 00:29:43,557 INFO    Thread-157 (_run_job):1788 [wandb_init.py:init():788] sending inform_init request
2025-04-14 00:29:43,558 INFO    Thread-157 (_run_job):1788 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-04-14 00:29:43,561 INFO    Thread-157 (_run_job):1788 [wandb_init.py:init():798] backend started and connected
2025-04-14 00:29:43,562 INFO    Thread-157 (_run_job):1788 [wandb_run.py:_config_callback():1261] config_cb None None {'activationFunction': 'GELU', 'batchNormalisation': 'no', 'dataAugmentation': 'no', 'dropout': 0.3, 'filterOrganisation': 'same', 'filters': 64}
2025-04-14 00:29:43,565 INFO    Thread-157 (_run_job):1788 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-04-14 00:29:43,584 INFO    Thread-157 (_run_job):1788 [wandb_init.py:init():891] updated telemetry
2025-04-14 00:29:43,667 INFO    Thread-157 (_run_job):1788 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-04-14 00:29:45,124 INFO    Thread-157 (_run_job):1788 [wandb_init.py:init():990] starting run threads in backend
2025-04-14 00:29:45,349 INFO    Thread-157 (_run_job):1788 [wandb_run.py:_console_start():2375] atexit reg
2025-04-14 00:29:45,350 INFO    Thread-157 (_run_job):1788 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-14 00:29:45,351 INFO    Thread-157 (_run_job):1788 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-14 00:29:45,352 INFO    Thread-157 (_run_job):1788 [wandb_run.py:_redirect():2315] Redirects installed.
2025-04-14 00:29:45,353 INFO    Thread-157 (_run_job):1788 [wandb_init.py:init():1032] run started, returning control to user process
2025-04-14 00:29:45,353 INFO    Thread-157 (_run_job):1788 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002945-cziyfmuk\logs\debug.log
2025-04-14 00:29:45,353 INFO    Thread-157 (_run_job):1788 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\DA6401_ASSIGNMENT2\wandb\run-20250414_002945-cziyfmuk\logs\debug-internal.log
2025-04-14 00:29:45,353 INFO    Thread-157 (_run_job):1788 [wandb_init.py:init():761] calling init triggers
2025-04-14 00:29:45,353 INFO    Thread-157 (_run_job):1788 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'GELU', 'batchNormalisation': 'no', 'dataAugmentation': 'no', 'dropout': 0.3, 'filterOrganisation': 'same', 'filters': 64}
config: {'filters': 32, 'activationFunction': 'ReLU', 'filterOrganisation': 'same', 'dataAugmentation': 'yes', 'batchNormalisation': 'yes', 'dropout': 0.2, '_wandb': {}}
2025-04-14 00:29:45,353 INFO    Thread-157 (_run_job):1788 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-04-14 00:29:47,189 INFO    Thread-157 (_run_job):1788 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment2/cziyfmuk
2025-04-14 00:29:47,199 ERROR   Thread-157 (_run_job):1788 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-04-14 00:29:47,199 INFO    Thread-157 (_run_job):1788 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-04-14 00:29:47,199 INFO    Thread-157 (_run_job):1788 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-04-14 00:29:47,199 INFO    Thread-157 (_run_job):1788 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-04-14 00:29:47,199 INFO    Thread-157 (_run_job):1788 [wandb_run.py:_restore():2322] restore
2025-04-14 00:29:47,199 INFO    Thread-157 (_run_job):1788 [wandb_run.py:_restore():2328] restore done
2025-04-14 00:29:49,280 INFO    Thread-157 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-04-14 00:29:49,280 INFO    Thread-157 (_run_job):1788 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-04-14 00:29:49,280 INFO    Thread-157 (_run_job):1788 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-04-14 00:29:49,289 ERROR   MainThread:1788 [pyagent.py:_run_jobs_from_queue():234] Run cziyfmuk errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\2340083540.py", line 36, in sweep_hyperparameters
    train_loss = train(model, train_loader, criterion, optimizer, device)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\427213304.py", line 7, in train
    outputs = model(images)
              ^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_1788\2929947945.py", line 36, in forward
    x = self.fc(x)
        ^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\container.py", line 250, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Python312\Lib\site-packages\torch\nn\modules\linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x262144 and 3211264x10)

2025-04-14 00:29:49,289 ERROR   MainThread:1788 [pyagent.py:_run_jobs_from_queue():245] Detected 3 failed runs in the first 60 seconds, killing sweep.
